Update lecaa

diff --git a/lecaa b/lecaa
--- a/lecaa
+++ b/lecaa
@@ -6,10 +6,15 @@ host=${arrIN[0]};
 port=${arrIN[1]};
 [ -z "$port" ] && port=443
 
-out=$(openssl s_client -connect "$host:$port" -servername "$host" -showcerts </dev/null 2>/dev/null | openssl x509 -text -noout | grep -A 1 Serial\ Number | tr -d : | tr -d ' ' | tail -n 1)
+echo
+echo testing $host:$port ...
 
-[ -z "$out" ] && exit
+out=$(openssl s_client -connect "$host:$port" -servername "$host" -showcerts </dev/null 2>/dev/null | openssl x509 -text -noout | grep -A 1$
+
+[ -z "$out" ] && echo "Failed connect $host:$port (zero output)" && exit
 
 look "$out" lecaa-serials.txt > /dev/null
 
-[ "$?" -eq 0 ] && echo "$1" "$out" affected
+[ "$?" -eq "0" ] && echo "Affected certificate $out $host" 
+
+echo ok!
